version: "3.8"

services:
  db:
    image: postgres:15
    container_name: catan-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catan_db
    ports:
        - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: catan-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/catan_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
    postgres-data: